name: Go-Windows
on:
  push:
    branches: [master]
  pull_request:
    branches: ["*"]
jobs:
  build-and-test-windows:
    name: Build Windows and test
    runs-on: windows-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        # lint-with-docker doesn't work on mac/win github actions. Just run test only.
        run: make test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
